l=[]
f1=input("Enter first name:")
l.append(f1)
f1=input("Enter first name:")
l.append(f1)
f1=input("Enter first name:")
l.append(f1)
f1=input("Enter first name:")
l.append(f1)
f1=input("Enter first name:")
l.append(f1)
f1=input("Enter first name:")
l.append(f1)
print(l)
print(type(l))


s=set()
s1=int(input("Enter first number:"))
s.add(s1)
s1=int(input("Enter first number:"))
s.add(s1)
s1=int(input("Enter first number:"))
s.add(s1)
s1=int(input("Enter first number:"))
s.add(s1)
s1=int(input("Enter first number:"))
s.add(s1)
s1=int(input("Enter first number:"))
s.add(s1)

print(s)
print(type(s))